name: Trigger auto deployment for ruby-container-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - '**'
    - '.github/workflows/ruby-container-app-AutoDeployTrigger-4f2fa91c-7f96-461e-adfb-fbaeb4897a3c.yml'

  # Allow mannually trigger 
  workflow_dispatch:      

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to container registry
        uses: docker/login-action@v1
        with:
          registry: ibersanoimages.azurecr.io
          username: ${{ secrets.RUBYCONTAINERAPP_REGISTRY_USERNAME }}
          password: ${{ secrets.RUBYCONTAINERAPP_REGISTRY_PASSWORD }}

      - name: Build and push container image to registry
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ibersanoimages.azurecr.io/ruby-container-app:${{ github.sha }}
          file: ./Dockerfile
          context: ./


  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.RUBYCONTAINERAPP_AZURE_CREDENTIALS }}


      - name: Deploy to containerapp
        uses: azure/CLI@v1
        with:
          inlineScript: |
            az config set extension.use_dynamic_install=yes_without_prompt
            az containerapp registry set -n ruby-container-app -g test-apps --server ibersanoimages.azurecr.io --username  ${{ secrets.RUBYCONTAINERAPP_REGISTRY_USERNAME }} --password ${{ secrets.RUBYCONTAINERAPP_REGISTRY_PASSWORD }}
            az containerapp update -n ruby-container-app -g test-apps --image ibersanoimages.azurecr.io/ruby-container-app:${{ github.sha }}
